# Generated by Django 5.2.9 on 2026-01-12 14:59

import django.core.validators
import users.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Товары в корзине',
                'verbose_name_plural': 'Товары в корзине',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Название категории')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код валюты')),
                ('symbol', models.CharField(max_length=5, verbose_name='Символ')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('rate_to_rub', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс к рублю')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная сумма для товара')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления курса')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40, verbose_name='Название купона')),
                ('stripe_coupon_id', models.CharField(blank=True, editable=False, max_length=100, verbose_name='ID купона в Stripe')),
                ('amount_off', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма скидки')),
                ('percent_off', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки')),
                ('duration', models.CharField(choices=[('forever', 'Навсегда'), ('once', 'Один раз'), ('repeating', 'Повторяющийся')], default='forever', max_length=10, verbose_name='Длительность действия')),
                ('duration_in_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество месяцев')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Купон',
                'verbose_name_plural': 'Купоны',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, validators=[users.validators.RussianValidator()], verbose_name='Название товара')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Цена')),
                ('description', models.TextField(blank=True, max_length=300, verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('is_available', models.BooleanField(default=True, verbose_name='Доступен для продажи')),
                ('image', models.ImageField(blank=True, upload_to='items/%Y/%m/%d/', verbose_name='Изображение')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='URL')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stripe_session_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID сессии Stripe')),
                ('stripe_payment_intent_id', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='ID платежа Stripe')),
                ('status', models.CharField(choices=[('Unpaid', 'Не оплачен'), ('Paid', 'Оплачен')], default='Unpaid', max_length=20, verbose_name='Статус')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Общая сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('item_name', models.CharField(max_length=200, verbose_name='Название товара')),
            ],
            options={
                'verbose_name': 'Товар в заказе',
                'verbose_name_plural': 'Товары в заказе',
            },
        ),
        migrations.CreateModel(
            name='RankCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('min_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная сумма')),
            ],
            options={
                'verbose_name': 'Категория ранга',
                'verbose_name_plural': 'Категории рангов',
                'ordering': ['min_total'],
            },
        ),
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50, verbose_name='Название')),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процентная ставка')),
                ('stripe_tax_id', models.CharField(blank=True, editable=False, max_length=100, verbose_name='ID в Stripe')),
                ('inclusive', models.BooleanField(default=False, verbose_name='Включение в цену')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1', max_length=2, null=True, verbose_name='Код страны')),
                ('description', models.TextField(blank=True, max_length=150, null=True, verbose_name='Описание')),
                ('jurisdiction', models.CharField(blank=True, max_length=50, null=True, verbose_name='Юрисдикция')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Регион (Штат)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Налог',
                'verbose_name_plural': 'Налоги',
            },
        ),
    ]
