# Generated by Django 5.2.9 on 2026-01-08 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tax',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=50, verbose_name='Название')),
                ('percentage', models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='Процентная ставка')),
                ('stripe_tax_id', models.CharField(blank=True, editable=False, max_length=100, verbose_name='ID в Stripe')),
                ('inclusive', models.BooleanField(default=False, editable=False, verbose_name='Включение в цену')),
                ('active', models.BooleanField(default=True, verbose_name='Активен')),
                ('country', models.CharField(blank=True, help_text='ISO 3166-1', max_length=2, null=True, verbose_name='Код страны')),
                ('description', models.TextField(blank=True, max_length=150, null=True, verbose_name='Описание')),
                ('jurisdiction', models.CharField(blank=True, max_length=50, null=True, verbose_name='Юрисдикция')),
                ('state', models.CharField(blank=True, max_length=50, null=True, verbose_name='Регион (Штат)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Налог',
                'verbose_name_plural': 'Налоги',
            },
        ),
    ]
