# Generated by Django 5.2.9 on 2026-01-09 07:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название купона')),
                ('stripe_coupon_id', models.CharField(blank=True, editable=False, max_length=100, verbose_name='ID купона в Stripe')),
                ('amount_off', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Сумма скидки')),
                ('percent_off', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процент скидки')),
                ('currency', models.CharField(blank=True, choices=[('usd', 'USD - Доллар США'), ('eur', 'EUR - Евро'), ('rub', 'RUB - Рубль'), ('gbp', 'GBP - Фунт стерлингов'), ('jpy', 'JPY - Иена'), ('aud', 'AUD - Австралийский доллар'), ('cad', 'CAD - Канадский доллар')], max_length=3, null=True, verbose_name='Валюта')),
                ('duration', models.CharField(choices=[('forever', 'Навсегда'), ('once', 'Один раз'), ('repeating', 'Повторяющийся')], default='once', max_length=10, verbose_name='Длительность действия')),
                ('duration_in_months', models.PositiveIntegerField(blank=True, null=True, verbose_name='Количество месяцев')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Скидка/Купон',
                'verbose_name_plural': 'Скидки/Купоны',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='tax',
            name='inclusive',
            field=models.BooleanField(default=False, verbose_name='Включение в цену'),
        ),
        migrations.AlterField(
            model_name='tax',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Процентная ставка'),
        ),
    ]
