# Generated by Django 5.2.9 on 2026-01-09 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_discount_alter_tax_inclusive_alter_tax_percentage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='discount',
            options={'ordering': ['-created_at'], 'verbose_name': 'Купон', 'verbose_name_plural': 'Купоны'},
        ),
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'USD - Доллар США'), ('eur', 'EUR - Евро'), ('rub', 'RUB - Рубль')], max_length=3, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'USD - Доллар США'), ('eur', 'EUR - Евро'), ('rub', 'RUB - Рубль')], max_length=3, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='duration',
            field=models.CharField(choices=[('forever', 'Навсегда'), ('once', 'Один раз'), ('repeating', 'Повторяющийся')], default='forever', max_length=10, verbose_name='Длительность действия'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='name',
            field=models.CharField(max_length=40, verbose_name='Название купона'),
        ),
    ]
