# Generated by Django 5.2.9 on 2026-01-09 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_discount_options_item_currency_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='taxes',
            field=models.ManyToManyField(blank=True, related_name='items', to='shop.tax', verbose_name='Налоги'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', '$'), ('eur', '€'), ('rub', '₽')], max_length=3, null=True, verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', '$'), ('eur', '€'), ('rub', '₽')], max_length=3, null=True, verbose_name='Валюта'),
        ),
    ]
