# Generated by Django 5.2.9 on 2026-01-10 15:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_cart_options_alter_cartitem_options_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RankCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название категории')),
                ('min_total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная сумма')),
                ('discount', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.discount', verbose_name='Скидка')),
            ],
            options={
                'verbose_name': 'Категория ранга',
                'verbose_name_plural': 'Категории рангов',
                'ordering': ['min_total'],
            },
        ),
    ]
