# Generated by Django 5.2.9 on 2026-01-10 16:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_rankcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=3, unique=True, verbose_name='Код валюты')),
                ('symbol', models.CharField(max_length=5, verbose_name='Символ')),
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('rate_to_rub', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс к рублю')),
                ('min_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Минимальная сумма для товара')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления курса')),
            ],
            options={
                'verbose_name': 'Валюта',
                'verbose_name_plural': 'Валюты',
                'ordering': ['code'],
            },
        ),
        migrations.AlterField(
            model_name='rankcategory',
            name='discount',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.discount', verbose_name='Купон'),
        ),
    ]
