# Generated by Django 5.2.9 on 2026-01-10 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_currency_alter_rankcategory_discount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['-created_at'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='currency',
            name='rate_to_rub',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Курс к рублю'),
        ),
        migrations.AlterField(
            model_name='discount',
            name='currency',
            field=models.ForeignKey(blank=True, limit_choices_to={'is_active': True}, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='item',
            name='currency',
            field=models.ForeignKey(limit_choices_to={'is_active': True}, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='shop.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='shop.currency', verbose_name='Валюта'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='currency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.currency', verbose_name='Валюта'),
        ),
    ]
